version: '3'
services:
  shoppy-app:
    build: .
    image: shoppy-app
    ports:
      - '3000:3000'
      - '9229:9229'
#    restart: always
    volumes:
      - .:/app
      - /app/node_modules
#    command: npm run start:debug
    environment:
      - MONGO_URI=${DOCKER_MONGO_URI}
    depends_on:
      - shoppy-mongo
  shoppy-mongo:
    image: mongo
    ports:
      - '27017:27017'
