version: '3'
services:
  shoppy-app:
    build: .
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - shoppy-mongo
  shoppy-mongo:
    image: mongo
    ports:
      - '27017:27017'
